### ISSUE TITLE
Need to move pt-br string to values-pt-rBR/strings.xml and create English strings.

### ISSUE THREAD

**Issue by henriquenfaria** [thiagoprochnow/carteiradeativos#13]
Currently, we're using values/strings.xml for pt-BR. Our app should have at least English and PT-BR.

**Comment by thiagoprochnow** [comment]
commit 4e1c7906857f430f8d3c45792895525ac4f40607
Created the string files for Portugues Brasil and English. Also made
the default value to be english.
