### ISSUE TITLE
Add Stock form buy date must call a date picker. The default date should be today.

### ISSUE THREAD

**Issue by henriquenfaria** [thiagoprochnow/carteiradeativos#17]

**Comment by thiagoprochnow** [comment]
commit a1724e605e4f7c7e8648cb3c4c7c37e0ebade85c

Created DatePicker Spinner function when clicking on EditText Field.
When clicking on select date field on the FormFragment, a Spinner
DatePicker will appear for the user to select the date he bought the
investment.
