### ISSUE TITLE
Current stock list layout is broken

### ISSUE THREAD

**Issue by henriquenfaria** [thiagoprochnow/carteiradeativos#27]
Stock list layout should be improved to fix items alignment.
There are several items being displayed in two lines, instead of one, for example.
Also, some items are being cropped in the sides.

**Comment by henriquenfaria** [comment]
![broken_layout](https://cloud.githubusercontent.com/assets/1030977/22406965/3da105f4-e644-11e6-850f-1aa70a4ba734.png)

**Comment by thiagoprochnow** [comment]
commit d75c372f932ce74a3e75c958517615c09ae0568b

Made changes on width sizes and added android:ellipsize="end" and
android:maxLines="1" to prevent layout break when max width is reached.
