### ISSUE TITLE
Whe should hightlight incorrect form fields when adding stocks 

### ISSUE THREAD

**Issue by henriquenfaria** [thiagoprochnow/carteiradeativos#29]
This could help user correct the wrong/incomplete form field. Without it, user could not understand what he's filling wrong in the form.

**Comment by thiagoprochnow** [comment]
commit by Walter by f380b7ca0bac05aac97c946c8b37557dee6ac328
@walternunes, please submit strings in pt-br and close this issue.

**Comment by walternunes** [comment]
done in 671922a5c2e5f0d09ab12986d5cf498505547ef3
