### ISSUE TITLE
Merge Statistics with Complete Portfolio?

### ISSUE THREAD

**Issue by henriquenfaria** [thiagoprochnow/carteiradeativos#32]
This is an idea to simplify our option. Maybe we don't need a separed section for statistics.
Maybe we should add those statistics inside Complete Portfolio section.

Let's discuss about.

**Comment by thiagoprochnow** [comment]
I think it is a good ideia. Maybe a new tab in the Complete Portfolio section.

**Comment by henriquenfaria** [comment]
Statistics option removed.
commit 09bb338
