### ISSUE TITLE
Start the development of Details of Stock

### ISSUE THREAD

**Issue by thiagoprochnow** [thiagoprochnow/carteiradeativos#36]
When clicking on a the stock cardview, should open a new activity to show more datails of that stock like:
- Buy dates and values, Medium Price (Preço Médio), Gain on that stock, gain on separate stock buys, Graph.
- Incomes, Income Graph.
This activity will also have option menu on toolbar for "Register Incomes, Bonification, Buy Stocks, Sell Stocks, Unfolding, Grouping"

**Comment by henriquenfaria** [comment]
For graphs: My suggestion is to use https://github.com/PhilJay/MPAndroidChart
I've used this lib in the past. It's fast and easy to implement.

**Comment by thiagoprochnow** [comment]
Necessary to create the options for Dividensd, JCP, Bonification. Needs to be done first, at least the basic part.

**Comment by thiagoprochnow** [comment]
commit 65a3d5275a636336e998a99bdaa7c5d4b5ce131b
commit 465f6c12532d41b878fa37745f69aed0c267ad41
