### ISSUE TITLE
Change Stock add, so if stock already added, it will sum to the portfolio

### ISSUE THREAD

**Issue by thiagoprochnow** [thiagoprochnow/carteiradeativos#40]
Right now, if a user adds 100 of ITUB4 stock and afterwards adds 200 of ITUB4, it will show as a total of 200 ITUB4. 
The correct approch would be to have the sum of both values as total.
Also, it is needed that both values are stored separately on database as for example:

ITUB4, 100, ... 23.50, 10/04/2015
ITUB4, 200, ... 27.62, 17/08/2016

And on the portfolio will show ITUB4 as 300 quantity.

**Comment by henriquenfaria** [comment]
Yes, it makes sense. On stock list it should display the total ammount. In the details screen we can specify the stock purchase dates and the ammount bought.

**Comment by walternunes** [comment]
If the stock list shows the Total ammount, how to calculate the other fields like V R G ?

**Comment by walternunes** [comment]
In DbHelper.java, the following line should be removed because the Symbol collumn will not be unique anymore:

"UNIQUE (" + PortfolioContract.StockQuote._ID + ") ON CONFLICT REPLACE);";

Before modify, please check if this is the expected behavior.

**Comment by thiagoprochnow** [comment]
"If the stock list shows the Total ammount, how to calculate the other fields like V R G ?"

As for this question, they have to be calculated separatly.
Example:
Current price for ITUB4 R$45,00
ITUB4 100 bought at R$30,00
ITUB4 200 bought at R$40,00
Average Price = (200\*40 + 100\*30)/(200+100) = R$36,67
**V**alorização = (CP - AP)/AP = (45-36,67)/36,67= 0,2271 = +22,71%

**R**endimetos will be a little more complicated:
We will have to match the ex dividend date with the bought date of the owned stocks.
Example:
ITUB4 Dividend of 0,45/stock with ex date at 05/05/2017 and receive date at 15/05/2017
ITUB4 100 bought at 02/05/2017
ITUB4 200 bought at 06/05/2017
Will receive only 100*0,45 at 15/05/2017

**Comment by thiagoprochnow** [comment]
commit ff6ffeb24f7e10aad7e4206897f7751ede5b8035
commit 45b5f4a062b3b84b78da072c65fa45d4d7f70cdf
