### ISSUE TITLE
Store buy date on the database

### ISSUE THREAD

**Issue by thiagoprochnow** [thiagoprochnow/carteiradeativos#41]
- Need to change code to also store the buy date of the stock.
- Now it is also needed to store the dividend receive date.

**Comment by henriquenfaria** [comment]
Related to issue #40

**Comment by henriquenfaria** [comment]
Need to store the date as milliseconds. Need to create Utils methods to convert millis value to a date (same timezone as the user).

**Comment by thiagoprochnow** [comment]
Timezone is not important.
Date value needed is only day/month/year
time is not important on stock buy, only date bought

**Comment by thiagoprochnow** [comment]
Done for stock by commit c0face678d59600cf1c0fd9ad779e072e523f87c
Need to do for incomes now.

**Comment by thiagoprochnow** [comment]
commit 9e74958c84988bf005a3898f2a33fd94b27aaff6
