### ISSUE TITLE
Delete is not working

### ISSUE THREAD

**Issue by walternunes** [thiagoprochnow/carteiradeativos#48]
Delete is not working due to a non existing URI in the provider. 

In my opinion it is not necessary to delete the register of table Symbol

**Comment by thiagoprochnow** [comment]
commit 816d1bfe1f5f6e4cc80096cf0d4a94a74300b67e

It was not working because deleting from "Symbols" table missing
deleting content with specific symbol URI.
Fixed it by adding PATH_STOCK_SYMBOLS_WITH_SYMBOL
