### ISSUE TITLE
No need to use compile br.com.livroandroid:android-utils

### ISSUE THREAD

**Issue by walternunes** [thiagoprochnow/carteiradeativos#5]
There is no need to use the components of  'br.com.livroandroid:android-utils:1.0.5'. I also don't know if the license if Opensource usage. 

If possible try to remove it

**Comment by thiagoprochnow** [comment]
I tried removing it, but the project would not compile due to some dependency of the package. I will try to remove the dependency first and then remove this package.

**Comment by thiagoprochnow** [comment]
Removed dependancy of br.com.livroandroid:android-utils by commit 005ecaa3d26fc7908d4c5ff29c3f42f510029032
